name = "pmp_check"
description = ""
version = "0.1.0-dev"

authors = ["Guillermo Vidal Sulé"]
maintainers = ["Guillermo Vidal Sulé <guillermo.vidal@bsc.es>"]
maintainers-logins = ["github-username"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["pmp_check"]
